flask_notes/large_project_framework/myproject/models.py
from myproject import database

class Puppy(database.Model):

    __tablename__ = 'puppies'

    id = database.Column(database.Integer,primary_key=True)
    name = database.Column(database.Text)
    owner = database.relationship('Owner',backref='puppy',uselist=False)

    def __init__(self,name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f'Puppy name is {self.name} and owner is {self.owner.name}.'

        else:
            return f'Puppy name is {self.name} and has no owner.'

class Owner(database.Model):

    __tablename__ = 'owners'

    id = database.Column(database.Integer,primary_key=True)
    name = database.Column(database.Text)
    puppy_id = database.Column(database.Integer,database.ForeignKey('puppies.id'))

    def __init__(self,name,puppy_id):
        self.name = name
        self.puppy_id = puppy_id

    def __repr__(self):
        return f'Owner name is: {self.name} and owns puppy id {self.puppy_id}'

flask_notes/large_project_framework/myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField('Name of Owner:')
    puppy_id = IntegerField('Id of Puppy')
    submit = SubmitField('Add Owner')

class DelForm(FlaskForm):
    id = IntegerField('Id Number of Owner to Remove: ')
    submit = SubmitField('Remove Owner')

flask_notes/large_project_framework/myproject/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField('Name of Puppy: ')
    submit = SubmitField('Add Puppy')

class DelForm(FlaskForm):
    id = IntegerField('Id Number of Puppy to Remove: ')
    submit = SubmitField('Remove Puppy')

flask_notes/large_project_framework/myproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

app.config['SECRET_KEY'] = 'secretkey'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///"+os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

database = SQLAlchemy(app)
Migrate(app,database)

# NOTE! These imports need to come after you've defined db, otherwise you will
# get errors in your models.py files.
## Grab the blueprints from the other views.py files for each "app"

from myproject.puppies.views import puppies_blueprint
from myproject.owners.views import owners_blueprint

app.register_blueprint(puppies_blueprint,url_prefix='/puppies')
app.register_blueprint(owners_blueprint,url_prefix='/owners')

flask_notes/large_project_framework/myproject/owners/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import database
from myproject.models import Owner
from myproject.owners.forms import AddForm, DelForm

owners_blueprint = Blueprint('owners',__name__,template_folder='templates/owners')
@owners_blueprint.route('/')
def list():
    owners = Owner.query.all()
    return render_template('list_owner.html',owners=owners)

@owners_blueprint.route('/add',methods=['GET','POST'])
def add():
    form = AddForm()
    if form.validate_on_submit():
        database.session.add(Owner(form.name.data,form.puppy_id.data))
        database.session.commit()

        return redirect(url_for('owners.list'))
    return render_template('add_owner.html',form=form)

@owners_blueprint.route('/delete',methods=['GET','POST'])
def delete():
    form = DelForm()
    if form.validate_on_submit():
        owner = Owner.query.get(form.id.data)
        database.session.delete(owner)
        database.session.commit()

        return redirect(url_for('owners.list'))
    return render_template('delete_owner.html',form=form)

flask_notes/large_project_framework/myproject/puppies/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import database
from myproject.models import Puppy
from myproject.puppies.forms import AddForm, DelForm

puppies_blueprint = Blueprint('puppies',__name__,template_folder='templates/puppies')
@puppies_blueprint.route('/')
def list():
    puppies = Puppy.query.all()
    return render_template('list.html',puppies=puppies)

@puppies_blueprint.route('/add',methods=['GET','POST'])
def add():
    form = AddForm()
    if form.validate_on_submit():
        database.session.add(Puppy(form.name.data))
        database.session.commit()

        return redirect(url_for("list"))
    return render_template('add.html',form=form)

@puppies_blueprint.route('/delete',methods=['GET','POST'])
def delete():
    form = DelForm()
    if form.validate_on_submit():
        pup = Puppy.query.get(form.id.data)
        database.session.delete(pup)
        database.session.commit()

        return redirect(url_for('list'))
    return render_template('delete.html',form=form)

flask_notes/large_project_framework/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Bootstrap CSS, JS, and jQuery -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{url_for('index')}}" style="color:white">Home Page</a>
         <div class="dropdown">
          <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton_puppy" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Puppy Pages
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton_puppy">
            <a class="dropdown-item" href="{{url_for('puppies.list')}}">Puppies</a>
            <a class="dropdown-item" href="{{url_for('puppies.add')}}">Add Puppy</a>
            <a class="dropdown-item" href="{{url_for('puppies.delete')}}">Delete Puppy</a>
          </div>
        </div>

        <div class="dropdown" style='margin:5px;'>
         <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenuButton_owner" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           Owner Pages
         </button>
         <div class="dropdown-menu" aria-labelledby="dropdownMenuButton_owner">
           <a class="dropdown-item" href="{{url_for('owners.list')}}">Owners</a>
           <a class="dropdown-item" href="{{url_for('owners.add')}}">Add Owner</a>
           <a class="dropdown-item" href="{{url_for('owners.delete')}}">Delete Owner</a>
         </div>
       </div>
      </nav>


  {% block content %}
  <div class="jumbotron">

  </div>
  {% endblock %}
  </body>
</html>

flask_notes/large_project_framework/myproject/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
  <h1>Home Page of Puppy Adoption Database</h1>
</div>
{% endblock %}